---
all:
  hosts:
    el-instance:
      ansible_host: 130.193.49.152
    ki-instance:
      ansible_host: 130.193.51.122
    app-instance:
      ansible_host: 51.250.13.52
  vars:
    ansible_connection: ssh
    ansible_user: debian
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    ki-instance:
app:
  hosts:
    app-instance: