{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m load" },
    { "expr": "node_load5", "legendFormat": "5m load" },
    { "expr": "node_load15", "legendFormat": "15m load" },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes\n-\nnode_memory_MemFree_bytes\n-\nnode_memory_Buffers_bytes\n-\nnode_memory_Cached_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Beffer" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cache" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=\"ext4\"}",
     "legendFormat": "Free space"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\"} - node_filesystem_avail_bytes{fstype=\"ext4\"}",
     "legendFormat": "Used space"
    }
   ]
  }
 ]
}