---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.107.22
    tc-agent:
      ansible_host: 84.201.142.20
      ansible_user: ubuntu
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
