filebeat.inputs:
  - type: container
#    encoding: utf8
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

#  - decode_json_fields:
#      fields: ["message"]
#      target: "json"
#      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5046"]

#output.console:
#  enabled: true
#  codec.json:
#    pretty: true

#logging.json: true
logging.metrics.enabled: false
